### ISSUE TITLE
product batch/lot and serial number

### ISSUE THREAD

**Issue by VladimirAlexiev** [w3c-ccg/traceability-vocab#279]
GTIN is class identifier, i.e. for a product "model" not an individual product. GS1 has extra identifiers:
- gs1:hasSerialNumber: together with `gtin` makes up SGTIN
- gs1:hasBatchLotNumber: together with `gtin` makes up LGTIN. This is especially used for food and produce, which often don't have individual SGTIN
- gs1:hasThirdPartyControlledSerialNumber: this makes up UPUI, used for cigarette packs imported to the EU 

I think you need to add these.

---

Searching for "serial" finds only 2 forms/documents, and "BIC ISO Container Identification".

Searching for "batch" finds [OGBillOfLading.yml](https://github.com/w3c-ccg/traceability-vocab/blob/main/docs/openapi/components/schemas/common/OGBillOfLading.yml)
```yml
batchNumber:
    title: Unique Well Identifier
    $linkedData:
      '@id': https://schema.org/identifier
```
That's a mistake because elsewhere you have
```yml
UWI:
  title: Unique Well Identifier
  $linkedData:
     '@id': https://schema.org/identifier
```
