### ISSUE TITLE
schemas must allow referencing in addition to nesting

### ISSUE THREAD

**Issue by VladimirAlexiev** [w3c-ccg/traceability-vocab#280]
If I'm not mistaken, the current schemas always specify nesting because you "include" other schemas.

In other words, you'd force me have this payload:
```
  id: did:example:BillOfLading:1234
  type: BillOfLading
  consignor:
    type: Entity
    id: did:web:ontotext.com
    name: Ontotext
    phone: blah

  id: did:example:Product:4321
  type: Product
  name: Ontotext GraphDB
  manufacturer: 
    type: Entity
    id: did:web:ontotext.com
    name: Ontotext
    phone: blah
```

But I'd much rather have this:
```
  id: did:web:ontotext.com
  type: Entity
  name: Ontotext
  phone: blah

  id: did:example:BillOfLading:1234
  type: BillOfLading
  consignor: did:web:ontotext.com

  id: did:example:Product:4321
  type: Product
  name: Ontotext GraphDB
  manufacturer: did:web:ontotext.com
```

Companies are certainly no less important than their products and shipping documents, so they deserve to have top-level nodes of their own.

JSONLD allows nesting, referencing, or combinations (e.g. I can nest the first instance in BillOfLading, and reuse it in Product). 
But IMHO your schemas allow only nesting.
