### ISSUE TITLE
QuantitativeValue.value should be a type:number, not type:string

### ISSUE THREAD

**Issue by nissimsan** [w3c-ccg/traceability-vocab#312]
Value being a string seems wrong: 
```
  value:
    title: Value
    description: Value or amount.
    type: string
    $linkedData:
      term: value
      '@id': https://schema.org/value
```
