### ISSUE TITLE
Address json-ld process issues with `oneOf` schema optionality

### ISSUE THREAD

**Issue by BenjaminMoe** [w3c-ccg/traceability-vocab#395]
### `oneOf` is poorly supported by OAS / JSON Schema processors

For example, this is what renders in JSON Schema form when you use oneOf:

![Screen Shot 2022-04-27 at 11 52 36 AM](https://user-images.githubusercontent.com/8295856/165579403-294d696e-633f-41cb-91fc-dc5c64fc02f2.png)

###  `oneOf` is not supported by the JSON-LD context builder

For example, this is the current context for `Entity`:

```
 "Entity": {
      "@id": "https://w3id.org/traceability#Entity",
      "@context": {}
    },
```

## Proposed Approaches to the Problem

**Approach 1:** Remove `oneOf` schema selection with a fixed option: oneOf is not supported by our JSON-LD processor  
Pull Request: https://github.com/w3c-ccg/traceability-vocab/pull/387  
Current Conclusion: Rejected as their are too many use-cases where an Entity could be a Person or an Organization, and we can't assert that in all cases it will only be an organization.

**Approach 2:** Allow json-ld processor to break in a way to default to a sane default  
Pull Request: https://github.com/w3c-ccg/traceability-vocab/pull/388  
Current Conclusion: Rejected as this does not address the underlying JSON Schema processors and JSON-LD context builder technical issue. 

**Approach 3**: Flatten schemas in a way that still allows for functionality without the use of `oneOf`  
Pull Request: https://github.com/w3c-ccg/traceability-vocab/pull/396  
Current Conclusion: This seems to be the most pragmatic approach for allowing optionality without implementing any changes to the JSON-LD processor. There are some opinions on the details, but there is consensus around this approach. 

**Approach 4**: Update JSON-LD processor to support `oneOf` schema functionality
Current Conclusion: No one has volunteered to implement this change

**Approach 5**: Add Enitity as a node, with subject be a ref Person or Organization

**Comment by OR13** [comment]
2 and 3 seem orthogonal to the main issue...


https://github.com/w3c-ccg/traceability-vocab/blob/4b17ce330bb6c804ef491d93e42c6a1f79584bec/docs/openapi/components/schemas/common/DCSAShippingInstruction.yml

[example](https://v.jsld.org/42Xv3ai3F8LeJaWu7mQnaGfvNJJXwE2UBtfgpo3EKjQuTrubCqzykxuwhEtfuXXZ772ZCmMoEtF2Ysn6PAjKzZKgRPo3VxrMKqJK7oYd2vLZ2VoPfUS7CEwBKLzKCQESTK7tWv6xhtRAMtY7F5UoivSo3kCvzMTgMdFmiz5t6SbVnY6y5bVmsqrq3tYYotjEf5oeMmrHarH8Pj4K5589soB9kT1n2Q6hCuimcS4zChFypdFJKKotuA974EyjHDLeDUkP6Fwg9SZDnWGSNfjxZ6bjsNixswbm4peDSXf1bDm8WTo8eC7E884ph9kA8WHuNkTN1fXotkGx3Dx4E9JsBAXq8xEEMimzK2o82gHpCgQLVMt5tznVq7j6YKaLT6F1eu1BoNwHxcDaX7xvbSeMG1Bk1y2NaJUecvarSyckaB22vCv5JeBz3U6UdepdL93hWXN1mtUbuSvjSyaKgq53ANfwxXoJisUz3boZFQGRPuDd52sVhDgL8dYo5oAqvKzNjX46P26k8XoCtjnQW2ahfoaiHyRMsMwmbN1j9QeKGX4fhMZpHXwAwGgwokSxkcVityRCSeQwRoDMJ87rLoBqxKhvrsQR65RNyV3atFgGesi1aAqjURw4PDhxMVw2F5TAzeXPY8xKocgBb5BEhK2Se1S7wpD8L9YivDKJkifjdtdgLt42RdhEKr9Kt3QaGiVSqVnWkXhWiCVVUsKbkRwLKEFnuTQtQE8bJhtR5nNcPJYqL9A8tgXZzm94ohrouXYh2EJ9HfR3G463wjCz8ikZs627QMEmrsp9Vsh9UerAxpRX2N7WPV8HG9ySEcsFkoKKP9K5mwVbcr16J193dGb1VK5jYHWSv61p5YTCSczohFajwEUpKvnGRyKLtMjqRhN1mDMGjUMJg4htvQhDVhXPyQfenXpK2ig1SJouhN7KjwWg2NtsrXAqySoiJSL5wN9b3bp5DZfVmp6GJzNf25e3qTqt4CHVUanvHBuGpzD5LenSsxdVwbzrRJVeHPB9JYsKeGMkLsv5i4T81YEDWyynL5DwLjVAayFsWYnPktxf1ou8ngScvgV822FW7WnZ2wiAXvqzp2iUyuegHVFrEP5CWN5mcR8yZ186tJaSdLSzqwVB4BsNvDhvUH9ssTXdH7C5RzpVB9nju2Z5bUDYmoxxiCYKtHozRQE4eaC6TZUs4W3AtwSobmQYNiEzwMX7DhM47km866YcW4kb6h8)

Here is the problem:

```

```

**Comment by OR13** [comment]
In practice we don't actually use "Entity" for any useful semantics... because it doesn't actually define any:

https://github.com/w3c-ccg/traceability-vocab/blob/4b17ce330bb6c804ef491d93e42c6a1f79584bec/docs/openapi/components/schemas/common/Entity.yml

https://github.com/w3c-ccg/traceability-vocab/blob/gh-pages/contexts/traceability-v1.jsonld#L709

```
 "Entity": {
      "@id": "https://w3id.org/traceability#Entity",
      "@context": {}
    },
```

All of the semantics are coming from "Person" or "Organization"... meaning we don't actually use Entity for anything other than schema validation... which has nothing to do with JSON-LD at all... but logically, we don't really want to be doing that... there are cases where you would want to know that an Organization and not a Person was handling something... 

Keeping oneOf in credentials means being ok with results like this:

```
{
    "type": "Person",
    "firstName": "Amelie"
}
```
^ If this is good enough for "Entity", I think we probably need to talk about what we are trying to do here.

**Comment by TallTed** [comment]
Re: "`oneOf` is not supported by _our_ JSON-LD processor" (https://github.com/w3c-ccg/traceability-vocab/issues/395#issue-1216458166) -- "our" should be replaced by a comprehensible identifier of the entity/ies whose JSON-LD processor does not support `oneOf`. This is necessary because, for instance, neither I nor my employer have participated in joint production of a JSON-LD processor, so it is not "our" processor when I speak of it.

-----

re "Here is the problem:" (https://github.com/w3c-ccg/traceability-vocab/issues/395#issuecomment-1110300096)

That is a bunch of triples. It is not a problem statement nor definition nor illustration. Please use plain language to state the problem which you apparently meant to illustrate by that dump of triples.

-----

Re: "being ok with results like this" (https://github.com/w3c-ccg/traceability-vocab/issues/395#issuecomment-1110305879): when a `Person` is the accurate `Entity` type (i.e., the `Entity` is *not* an `Organization`), it does not make sense to require the attributes of an `Organization`.  I fail to see why `oneOf (Person, Organization)` somehow makes the minimum required description of either the `Person` or `Organization` less than the minimum required description would be if the `oneOf` were dropped and either `Person` or `Organization` were always required.

It makes perfect sense to me to require some specific attributes of such an `Entity`; the specific list of which attributes are required would naturally vary with the subtype of that `Entity`, e.g., `Person` or `Organization` (there might be more relevant types that we haven't yet encountered in our far-from-exhaustive explorations), because, for instance, a `dateOfBirth` of a `Person` does not directly translate to `dateOfIncorporation` (or similar) for an `Organization`.  Likewise, while `firstName` does not make sense for `Organization` and is insufficient (among other things) for a `Person`, `legalName` _might_ make sense for either, and `address` _might_ make sense for neither.  (See https://github.com/kdeldycke/awesome-falsehood for more.)

-----

Re: "I think we probably need to talk about what we are trying to do here" (https://github.com/w3c-ccg/traceability-vocab/issues/395#issuecomment-1110305879) -- Yes, I think we probably do.

**Comment by OR13** [comment]
Another alternative solution would be to remove any $ref that yielded a descendent that contained oneOf from all the certificate types we (Transmute) support. 

This would not impact any of the other certificate types, and would resolve the broken behavior we are currently observing when handling the schemas in this repo, but only for "steel or e-commerce" certificates... which seems unhelpful. to others.

See the proposal here for the best path forward that I am aware of currently: https://github.com/w3c-ccg/traceability-vocab/pull/396

**Comment by BenjaminMoe** [comment]
@OR13 I was thinking as I wrote that I shouldn't use the PR page for issue discussion. 

My intended implementation of this would be merge `Organization` and `Person` into a new `Entity.yml` which would replace the existing `oneOf Entity.yml`. And then go back and re-generate all of the proofs. 

```yml
title: Entity
description: A merge of Person and Organization
type: object
  type:
    oneOf:
      - type: array
        items:
          type: string
          enum:
            - Entity
      - type: string
        const: Entity
  entityType:
    description: The type of entity
    type: string
    enum:
      - Person
      - Organization
  name:
    title: Name
    description: Name of the organization.
    type: string
    $linkedData:
      term: name
      '@id': https://schema.org/name
  legalName:
    title: Legal Name
    description: The official name of the organization, i.e., the registered company name.
    type: string
    $linkedData:
      term: legalName
      '@id': https://schema.org/legalName
  firstName:
    title: First Name
    description: Person's first name.
    type: string
    $linkedData:
      term: firstName
      '@id': https://schema.org/givenName
  lastName:
    title: Last Name
    description: Person's last name.
    type: string
    $linkedData:
      term: lastName
      '@id': https://schema.org/familyName
  email:
    title: Person's Email Address
    description: Person's email address.
    type: string
    $linkedData:
      term: email
      '@id': https://schema.org/email
  phoneNumber:
    title: Phone Number
    description: Person's contact phone number.
    type: string
    $linkedData:
      term: phoneNumber
      '@id': https://schema.org/telephone
  worksFor:
    title: Works For
    description: Company which employs the person.
    $ref: ./Organization.yml
    $linkedData:
      term: worksFor
      '@id': https://schema.org/worksFor
  jobTitle:
    title: Job Title
    description: Person's job title.
    type: string
    $linkedData:
      term: jobTitle
      '@id': https://schema.org/jobTitle
  leiCode:
    title: Legal Entity Identifier Code
    description: Legal entity identifier code
    type: string
    $linkedData:
      term: leiCode
      '@id': https://schema.org/leiCode
  url:
    title: URL
    description: URL of the organization.
    type: string
    $linkedData:
      term: url
      '@id': https://schema.org/url
  description:
    title: Description
    description: Description of the company.
    type: string
    $linkedData:
      term: description
      '@id': https://schema.org/description
  globalLocationNumber:
    title: Global Location Number
    description: The GS1 GLN of the organization.
    type: string
    $linkedData:
      term: globalLocationNumber
      '@id': https://schema.org/globalLocationNumber
  address:
    title: Postal Address
    description: The postal address for an organization or place.
    $ref: ./PostalAddress.yml
    $linkedData:
      term: address
      '@id': https://schema.org/PostalAddress
  faxNumber:
    title: Phone Number
    description: Organization's fax number.
    type: string
    $linkedData:
      term: faxNumber
      '@id': https://schema.org/faxNumber
  brand:
    title: Brand
    description: Branding for this organization
    $ref: ./Brand.yml
    $linkedData:
      term: brand
      '@id': https://schema.org/Brand
  contactPoint:
    title: Contact Point
    description: Points of contact for this organization
    $ref: ./ContactPoint.yml
    $linkedData:
      term: contactPoint
      '@id': https://schema.org/ContactPoint
  taxId:
    title: Tax Identification Number
    description: >-
      The Tax / Fiscal ID of the organization or person, e.g., the TIN in the US
      or the CIF/NIF in Spain.
    type: string
    $linkedData:
      term: taxId
      '@id': https://schema.org/taxID
  iataCarrierCode:
    title: IATA Carrier Code
    description: Carrier's three-digit IATA airline code number
    type: string
    $linkedData:
      term: iataCarrierCode
      '@id': https://onerecord.iata.org/cargo/Company#airlineCode
```

The intended reason for including all of these optional fields is it means that no change would be needed for the JSON examples, only the proofs would need to be updated for everything that's already using `Entity`.

**Comment by OR13** [comment]
I don't think we want this many optional fields in Entity... @mprorock has indicated that there is likely a minimal set of required fields that would meet the regulatory guidelines... I would like them encoded in a schema that marked them as required... and to avoid copy pasting `$ref: './Entity.yml'` all over the place, because it probably does not yield the kind of data a verifier / regulator would want to receive.

ideally we would use more inline restricted schemas, and less `$ref`.

**Comment by BenjaminMoe** [comment]
`Entity` is used in [Verifiable Business Card](https://github.com/w3c-ccg/traceability-vocab/blob/main/docs/openapi/components/schemas/common/VerifiableBusinessCard.yml#L31). I think we need the minimum requirements for defining an organization. 

```yml
title: Entity
description: A merge of Person and Organization
type: object
  type:
    oneOf:
      - type: array
        items:
          type: string
          enum:
            - Entity
      - type: string
        const: Entity
  entityType:
    description: The type of entity
    type: string
    enum:
      - Person
      - Organization
  name:
    title: Name
    description: Name of the organization.
    type: string
    $linkedData:
      term: name
      '@id': https://schema.org/name
  legalName:
    title: Legal Name
    description: The official name of the organization, i.e., the registered company name.
    type: string
    $linkedData:
      term: legalName
      '@id': https://schema.org/legalName
  url:
    title: URL
    description: URL of the person or organization.
    type: string
    $linkedData:
      term: url
      '@id': https://schema.org/url
  taxId:
    title: Tax Identification Number
    description: >-
      The Tax / Fiscal ID of the organization or person, e.g., the TIN in the US
      or the CIF/NIF in Spain.
    type: string
    $linkedData:
      term: taxId
      '@id': https://schema.org/taxID
```

**Comment by mprorock** [comment]
> `Entity` is used in [Verifiable Business Card](https://github.com/w3c-ccg/traceability-vocab/blob/main/docs/openapi/components/schemas/common/VerifiableBusinessCard.yml#L31). I think we need the minimum requirements for defining an organization would be.
> 
> ```yaml
> title: Entity
> description: A merge of Person and Organization
> type: object
>   type:
>     oneOf:
>       - type: array
>         items:
>           type: string
>           enum:
>             - Entity
>       - type: string
>         const: Entity
>   entityType:
>     description: The type of entity
>     type: string
>     enum:
>       - Person
>       - Organization
>   name:
>     title: Name
>     description: Name of the organization.
>     type: string
>     $linkedData:
>       term: name
>       '@id': https://schema.org/name
>   legalName:
>     title: Legal Name
>     description: The official name of the organization, i.e., the registered company name.
>     type: string
>     $linkedData:
>       term: legalName
>       '@id': https://schema.org/legalName
>   url:
>     title: URL
>     description: URL of the person or organization.
>     type: string
>     $linkedData:
>       term: url
>       '@id': https://schema.org/url
>   taxId:
>     title: Tax Identification Number
>     description: >-
>       The Tax / Fiscal ID of the organization or person, e.g., the TIN in the US
>       or the CIF/NIF in Spain.
>     type: string
>     $linkedData:
>       term: taxId
>       '@id': https://schema.org/taxID
> ```
> 
> We could keep a small number of well-defined requirements, and then just say `additionalProperties: true`.

Really close - TIN will be optional in many cases or will be PII.

We will also want to have explicit (optional?) fields for address/place, phone, and email, and likely a DID (though in our case the DID would be the id value)

Then the additionalProperties will take care of the rest

Pinging others to make sure i am not missing something critical for defining a Person or a Business
@rhofvendahl @brownoxford

**Comment by BenjaminMoe** [comment]
Sounds like

```
required:
- type
- entityType
- name
optional (defined):
- tax id number
- address
- phone
- email
- id / did / url(?)
```

**Comment by BenjaminMoe** [comment]
Got into this a little bit, and I think I understand part of the problem. The `Entity` type is not structured in a JSON-LD friendly way.

```
$linkedData:
  term: Entity
  '@id': https://w3id.org/traceability#Entity
title: Entity
description: A person or organization.
oneOf:
  - $ref: ./Person.yml
  - $ref: ./Organization.yml
example: |-
  {
    "type": "Person",
    "firstName": "Kane",
```

In this case all Entity is doing is passing through to `Person`, or `Organization`, and I don't think that JSON-LD supports this behavior on a fundamental level. We would need something closer to  the following. 

```
type: object
  type:
    oneOf:
      - type: array
        items:
          type: string
          enum:
            - Entity
      - type: string
        const: Entity
  subject:
    description: The type of entity
    oneOf:
        - $ref: ./Person.yml
        - $ref: ./Organization.yml
```

In order to have an `Entity` node, and then have `subject` stem from that. Since all of the schemas filter down to this reference, even a change like this requires a lot of work. I'm going to work towards flattening the schema as I think that is the lowest risk solution at this point.
