### ISSUE TITLE
How to define JSON-LD Classes so that no undefined terms are created related to "entityType"

### ISSUE THREAD

**Issue by BenjaminMoe** [w3c-ccg/traceability-vocab#528]

**Comment by OR13** [comment]
please kill this, somehow.

**Comment by OR13** [comment]
`entityType` is not allowed in any of "Transmute" credentials.

**Comment by BenjaminMoe** [comment]
https://github.com/w3c-ccg/traceability-vocab/blob/main/docs/openapi/components/schemas/common/Entity.yml#L14

```
  entityType:
    description: The type of entity
    type: string
    enum:
      - Person
      - Organization
    $linkedData:
      term: entityType
      '@id': https://schema.org/additionalType
```
