### ISSUE TITLE
Different betwen const and enum for type definitions

### ISSUE THREAD

**Issue by BenjaminMoe** [w3c-ccg/traceability-vocab#543]
### Example 1

```yml
  type:
    type: array
    const:
      - VerifiableCredential
      - VerifiableScorecard
```

produces the following in JSON schema:

```json
{
  "type": "array",
  "const": [ "VerifiableCredential", "VerifiableScorecard" ]
}
```

### Example 2

```yml
    items:
      type: string
      enum:
        - https://www.w3.org/2018/credentials/v1
        - https://w3id.org/traceability/v1
```

produces

```json
{
  "type": "array",
  "items": {
    "type": "string",
    "enum": ["VerifiableCredential", "VerifiableBusinessCard" ]
  }
}
```

### Action Item

Proposal, we should be consistent one way or the other in the `credential` directory. If const works, I'd lean towards that to say `type` **must be** these two values. Otherwise enum would imply one or more of these possible values.

**Comment by acarnagey** [comment]
I think we want to be as descriptive as possible for json schema form.  'readOnly' is important to say field can't be changed, default is important to say this is the value the field should have at the start, const means it can't have a different value if it did, and items enum means if you were able to add item to array you would only be able to assign those values to that item in the array.
```yaml
type: array
readOnly: true
const:
  - VerifiableCredential
  - VerifiableBusinessCard
default:
  - VerifiableCredential
  - VerifiableBusinessCard
items:
  type: string
  enum:
    - VerifiableCredential
    - VerifiableBusinessCard
```
