### ISSUE TITLE
wrong use of ItemList

### ISSUE THREAD

**Issue by VladimirAlexiev** [w3c-ccg/traceability-vocab#569]
The following schemas use https://schema.org/ItemList:
- AgricultureActivity.yml: 3
- AgriculturePackage.yml: 1
- ppq203.yml: 1
- PGAShipmentStatusList.yml: 1
- Phytosanitary.yml: 1

That's a rather specific class that should only be used for **ordered** lists, and there's no way to specify the class of elements.
More precisely, its `itemListElement` must be `ListItem`, which must have a `position` (integer) and `item` that's `Thing` (i.e. unspecific class).

Here are 2 specific cases to illustrate the error:

AgricultureActivity.yml:
```yaml
  actor:
    title: Actor
    description: The actual person or persons performing the activity.
    type: array
    items:
      $ref: ./Person.yml
    $linkedData:
      term: actor
      '@id': https://w3id.org/traceability#Person
      '@type': https://schema.org/ItemList
```
You cannot state "a list of Persons", and the `Person.yml` schema doesn't have any fields pertaining to ordered lists, nor does the example embedded in AgricultureActivity.yml.

```yaml
  pgaShipmentStatusItems:
    title: PGA Shipment Status Items
    description: List of PGA Status Messages pertaining to per-line items
    type: array
    items:
      $ref: ./PGAShipmentStatus.yml
    $linkedData:
      term: pgaShipmentStatusItems
      '@id': https://schema.org/ItemList
      '@type': https://schema.org/ItemList
```
The problems are the same.

---

If you need an ordered list of items, you can do specify this in the JSONLD context:
```json
"pgaShipmentStatusItems": {"@type":"@id", "@id","traceability:pgaShipmentStatusItems", "@collection":"@list"}
```
Then it will be emitted as an `rdf:List` that doesn't have integer `position` fields but uses a linked list to preserve order.
It looks nice in turtle, eg:
```ttl
<list> traceability:pgaShipmentStatusItems ("one" "two" "three")
```
But such list uses blank nodes and looks like the following RDF structure:
```ttl
<list> traceability:pgaShipmentStatusItems 
  [a rdf:List; rdf:first "one"; rdf:rest
    [a rdf:List; rdf:first "two"; rdf:rest
      [a rdf:List; rdf:first "three"; rdf:rest rdf:nil]]]
```
Despite JSONLD's syntactic support for rdf:List,
you probably will want to avoid it and use your own structure, eg a simplification of schema:ItemList:
```ttl
<list> a traceability:PGAShipmentStatusList traceability:member
  [a traceability:PGAShipmentStatus; traceability:position 1; traceability:recordNo: "SO701"...],
  [a traceability:PGAShipmentStatus; traceability:position 2; traceability:recordNo: "SO702"...],
  [a traceability:PGAShipmentStatus; traceability:position 3; traceability:recordNo: "SO703"...].
```

**Comment by brownoxford** [comment]
@rhofvendahl can you please take a peek at this?

**Comment by rhofvendahl** [comment]
@VladimirAlexiev Thanks for pointing this out, and for the explanation!

It looks as though the '@type' is used almost entirely for ItemList and identifier, both of which (as you've pointed out) are used incorrectly. Unless there are any objections I'd like to leave correct implementation of '@type' for future PRs and for now just remove the offending code.

**Comment by nissimsan** [comment]
`types` are now removed. 
But closing this issue. 
We might want to introduce types on a case by case bases on dedicated tickets.

**Comment by VladimirAlexiev** [comment]
@nissimsan it's still used in 7 schemas: https://github.com/w3c-ccg/traceability-vocab/search?q=ItemList&type=code
Please reopen.

**Comment by nissimsan** [comment]
Nice search, @VladimirAlexiev.

The simple solution seems to be just removing `'@type': https://schema.org/ItemList`?

**Comment by VladimirAlexiev** [comment]
I'm afraid that the https://github.com/w3c-ccg/traceability-vocab/pull/686 fix doesn't do much.

Another example from RevocationList2020Status.yml:
```yml
  revocationListIndex:
    title: revocationListIndex
    type: string
    $linkedData:
      term: revocationListIndex
      '@id': https://schema.org/itemListElement
  revocationListCredential:
    title: revocationListCredential
    type: string
    $linkedData:
      term: revocationListCredential
      '@id': https://schema.org/LinkRole
example: |-
  {
    "type" : ["RevocationList2020Status"],
    "revocationListIndex" : "0",
    "revocationListCredential": "https://example.gov/revocation-lists/urn:uuid:3bc24f87-b47b-43a0-b5bf-b9fde7913746"
  }
```
There are several mistakes here:
- the example suggests to map `revocationListIndex -> schema:position` and make it integer. As described above, `ItemListElement` points to https://schema.org/ListItem that includes two fields `position, item`. Where in the above do you see `item`?
- the prop `revocationListCredential` cannot be mapped to the class https://schema.org/LinkRole. Furthermore, when reading the definition (and even name) of that class, I don't see any relevance to the use shown above.
