### ISSUE TITLE
conflation of `value`

### ISSUE THREAD

**Issue by VladimirAlexiev** [w3c-ccg/traceability-vocab#575]
Similar to #571, some schemas map several terms to `schema:value`, which makes it impossible to distinguish these values in RDF.
Eg OFBillOfLading:
```yml
  valuePerItem:
    title: Value Per Item
    description: Value Per Item
    type: string
    $linkedData:
      term: valuePerItem
      '@id': https://www.schema.org/value
  totalOrderValue:
    title: Total Order Value
    description: Total value of the order
    type: string
    $linkedData:
      term: totalOrderValue
      '@id': https://www.schema.org/value
```
then in the example:
```json
    "valuePerItem": "500",
    "totalOrderValue": "1500",
```

This means that in RDF you cannot tell which number is which.
```[tasklist]
### Tasks
- [ ] @rhofvendahl creates an issue with checklist for aggriculture
- [ ] Ben and Nis create an issue with checklist for steel
```
