### ISSUE TITLE
declare enumerations

### ISSUE THREAD

**Issue by VladimirAlexiev** [w3c-ccg/traceability-vocab#577]
ImmediateDelivery.yml:
```
  transportMode:
    title: Mode Of Transportation
    description: The Mode of Transportation from the available options Air, Ocean, Rail, Truck, Hand Carry, Pipeline, or Other.
    type: string
    $linkedData:
      term: transportMode
      '@id': https://w3id.org/traceability#transportMode
```
The JSON type should be `enum` not mere string, and enumerate the allowed options.

---

If you want to capture this semantically, it gets more complex:
- make a skos:ConceptScheme for this enumeration, eg https://w3id.org/traceability#TransportMode (note the capital letter!)
- populate it with skos:Concept, eg

```ttl
<https://w3id.org/traceability#TransportMode> a skos:ConceptScheme;
  skos:prefLabel "Mode Of Transportation";
  skos:description: "Mode of Transportation as per TODO. Available options: Air, Ocean, Rail, Truck, Hand Carry, Pipeline, or Other";
  dct:source <TODO>.

<https://w3id.org/traceability#TransportMode-Air> a skos:Concept;
  skos:inScheme <https://w3id.org/traceability#TransportMode>;
  skos:prefLabel "Air";
  skos:definition "Air mode of transport".
```
- use an embedded context to map the terms, eg
```yml
    $linkedData:
      term: transportMode
      '@id': https://w3id.org/traceability#transportMode
      '@context': {'@vocab': https://w3id.org/traceability#transportMode- }
```

If you like Manu Sporny think that `@vocab` should be avoided, then you need to enumerate the terms:
```yml
      '@context':
        'Air': {'@type': '@id', '@id': https://w3id.org/traceability#transportMode-Air}
        ...
```

**Comment by brownoxford** [comment]
Discussed on call, unclear on action items

**Comment by nissimsan** [comment]
So, like 
```
  transportMode:
    title: Mode Of Transportation
    description: The Mode of Transportation from the available options Air, Ocean, Rail, Truck, Hand Carry, Pipeline, or Other.
    type:[Air, Ocean, Rail, Truck, Hand Carry, Pipeline, Other]
    $linkedData:
      term: transportMode
      '@id': https://w3id.org/traceability#transportMode
```
?
