### ISSUE TITLE
Date string should be switched to Datetime

### ISSUE THREAD

**Issue by BenjaminMoe** [w3c-ccg/traceability-vocab#593]
https://github.com/w3c-ccg/traceability-vocab/blob/main/docs/openapi/components/schemas/common/CTPAT.yml#L58

```yml
  dateOfLastValidation:
    title: Date of Last Validation
    description: >-
      Date of last validation.
    type: string
    $linkedData:
      term: dateOfLastValidation
      '@id': https://schema.org/Date
```

Value is a Datetime, should use Datetime for JSOn Schema 
`"dateOfLastValidation": "2022-01-06T11:50:00Z",`
