### ISSUE TITLE
Proposal: Update Tooling to separate Schema from Context

### ISSUE THREAD

**Issue by BenjaminMoe** [w3c-ccg/traceability-vocab#624]
## Description of Problem:

Right now we have JSON Schema and Context definitions in the same file. From working with this approach I think this creates some of the following problems.

1. **Bloat**. Anytime you use organization, you pull in things like LEI code or IATA code, which are required for specific credentials related to organizations, but not applicable to most (eg. "what i need an iata code to apply for an Organic Certification?). 
2. **Confusion** between wrapper and associated documents and RDF classes. `Bill of Lading Credential` outer wrapper versus the `Bill of Lading` schema used to defined the `credentialSubject`. 
3. **Confusion** with respect to the `$linkedData` element on our schema yml files with respect to `@id` and `@type`. 

## Proposal For Changes:

Summary Separate `@context` from JSON Schema. 

1. We have a directory of JSON files that define RDF classes that get built into a single `@context` file
2. We have a single directory for credential schema definitions
   - Schema definitions can reference other components for convenience
 
## Advantages of this Approach:

1. Addresses: https://github.com/w3c-ccg/traceability-vocab/issues/527
2. Allows for document specific requirements for optional and required fields

### How does this address Issue 527 (oneOf)

Given the following example context

```JSON
{
  "@context": {
    "@version": 1.1,
    "Organization": {
      "@id": "https://schema.org/Organization",
      "@context": {
        "name": {
          "@id": "https://schema.org/name"
        }
      }
    },
    "Person": {
      "@id": "https://schema.org/Person",
      "@context": {
        "name": {
          "@id": "https://schema.org/name"
        }
      }
    }
  }
}
```
Would allow you to define JSON context similar to the following:

```yml
title: Issuer
description: An issuer such as a person or organization
type: object
properties:
  type:
    type: array
    items:
      type: string
      enum:
        - Organization
        - Person
  id:
    title: Identifier
    description: Decentralized identifier for the issuer
    type: string
  name:
    title: Name
    description: Name of the issuer.
    type: string
additionalProperties: false
required:
  - id
  - type
  - name
example: |-
  {
    "id": "did:key:z6MktHQo3fRRohk44dsbE76CuiTpBmyMWq2VVjvV6aBSeE3U",
    "type": ["Person"],
    "name": "Glover - Gleason"
  }
```

Which would allow you to define either a `Person` or `Organization` for an issuer as these would reference an existing context. So by separating the JSON schema from the context definition would allow for expressions like this as defining a schema would not influence the context. 

### How this allows for per-document requirements

For the following example context:

```json
{
  "@context": {
    "@version": 1.1,
    "Organization": {
      "@id": "https://schema.org/Organization",
      "@context": {
        "name": {
          "@id": "https://schema.org/name"
        },
        "description": {
          "@id": "https://schema.org/description"
        },
        "globalLocationNumber": {
          "@id": "https://schema.org/globalLocationNumber"
        },
        "iataCarrierCode": {
          "@id": "https://onerecord.iata.org/cargo/Company#airlineCode"
        },
        "legalName": {
          "@id": "https://schema.org/legalName"
        },
        "leiCode": {
          "@id": "https://schema.org/leiCode"
        },
        "address": {
          "@id": "https://schema.org/address"
        },
        "taxId": {
          "@id": "https://schema.org/taxID"
        },
        "url": {
          "@id": "https://schema.org/url"
        }
      }
    }
  }
}
```

You could have the following different `Organization` schemas in separate documents with different descriptions and requirements

```yml
title: IATA Organization
description: An IATA organization
type: object
properties:
  type:
    type: array
    readOnly: true
    const:
      - Organization
    default:
      - Organization
    items:
      type: string
      enum:
        - Organization
  id:
    title: Identifier
    description:  Identifier for the organization
    type: string
  name:
    title: Name
    description: Name of the organization
    type: string
  iataCarrierCode:
    title: Carrier Code
    description: The carrier code for the company 
    type: string
  url:
    title: URL
    description: The url for the homepage of the company 
    type: string
additionalProperties: false
required:
  - id
  - type
  - name
  - iataCarrierCode
example: |-
  {
    "id": "did:key:z6MktHQo3fRRohk44dsbE76CuiTpBmyMWq2VVjvV6aBSeE3U",
    "type": ["Organization"],
    "name": "Example Airlines",
    "iataCarrierCode": "0001",
    "url": "https://example-airlines.example.com"
  }
```

```yml
title: CTPAT Organization
description: A CTPAT certified organization
type: object
properties:
  type:
    type: array
    readOnly: true
    const:
      - Organization
    default:
      - Organization
    items:
      type: string
      enum:
        - Organization
  id:
    title: Identifier
    description: identifier for the organization
    type: string
  name:
    title: Name
    description: Name of the organization.
    type: string
  address:
    title: Address
    description: The address of the company 
    type: 
      $ref ./address.yml
additionalProperties: false
required:
  - id
  - type
  - name
  - address
example: |-
  {
    "id": "did:key:z6MktHQo3fRRohk44dsbE76CuiTpBmyMWq2VVjvV6aBSeE3U",
    "type": ["Organization"],
    "name": "Glover - Gleason"
    "address": {
        "type": ["PostalAddress"],
        "streetAddress": "210 Jermey Fort",
        "addressLocality": "Lake Evalyn",
        "addressRegion": "Montana",
        "postalCode": "71172",
        "addressCountry": "US"
      }
  }
```

## Implications:

1. CI would need to be updated with the following changes
   - Examples MUST have valid schemas
   - Examples MUST have defined terms
1. CD will need to be changed to only build and reference from credential schema folder
1. `6. Vocabulary` section of the respec document will be removed
1. Schemas MUST have `additionalProperties` set to false

## Criteria

1. An agreement is made about the direction of this proposal
2. Separate issues are created to implement each one of the implications defined in this document
