### ISSUE TITLE
LEIentity: legalNameLanguage is wrong

### ISSUE THREAD

**Issue by VladimirAlexiev** [w3c-ccg/traceability-vocab#947]
This makes no sense since a prop is mapped to a class:
```yaml
  legalNameLanguage:
    title: Language
    type: string
    $linkedData:
      term: legalNameLanguage
      '@id': https://schema.org/Language
```
The examples look like:
```json
      "legalName": "Bashirian, Botsford and Hilll",
      "legalNameLanguage": "tr",
```
However, such representation goes against RDF `langString` literals that instead should be like this:
```json
      "legalName": {"@value": "Bashirian, Botsford and Hilll", "@language": "tr"},
```

If you look around https://www.gleif.org/ontology/v1.0/Base/index-en.html#hasNameLegal,
there's no separate field for the language because it should use the RDF lang tag.

This is the only place with this problem.
```
cd traceability-vocab/docs/openapi/components/schemas/common
grep -i "lang.*" *
```

`LEIaddress` has a field `language` but that's the language of all address fields, so there is some reason to keep it as is. @TallTed what do you think?
